// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID        int32
	Source    string
	Alias     string
	CreatedAt pgtype.Timestamp
}
