// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (source, alias) values ($1, $2) RETURNING id, source, alias, created_at
`

type CreateLinkParams struct {
	Source string
	Alias  string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Source, arg.Alias)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, source, alias, created_at FROM links where alias = $1
`

func (q *Queries) GetLink(ctx context.Context, alias string) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, alias)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}
